### ISSUE TITLE
 ¿Have anyone a example with marquez and amundsen?

### ISSUE THREAD

**Issue by HenrryVargas** [MarquezProject/marquez#1291] opened 2021-05-06 06:06 UTC
Hello ¿Have anyone a example with marquez and amundsen?

I'am using amundsen and I would to know how integrate both

thanks for the help

**Comment by mobuchowski** [comment] 2021-05-06 11:23
We don't have support for that right now. Hovewer, it's in our roadmap.

**Comment by HenrryVargas** [comment] 2021-06-04 12:32
@mobuchowski  thanks.

¿Have you any workaound to inspired me while you work in the integration?

Thanks

**Comment by mobuchowski** [comment] 2021-06-04 14:20
Unfortunately, Amundsen is not a simple system that could work easily with some workaround. 

To do a proper integration, it seems to me that way to do it is to bypass the databuilder framework and push directly to underlying database, such as Neo4j, or make Marquez backend for Metadata Service.

https://raw.githubusercontent.com/amundsen-io/amundsen/master/docs/img/Amundsen_Architecture.png

**Comment by julienledem** [comment] 2021-06-18 17:18
Marqueing as duplicate of : https://github.com/MarquezProject/marquez/issues/1423

**Closed by julienledem** 2021-06-18 17:18 UTC
