### ISSUE TITLE
Duplicate `type` field in `Node.Data`

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#1471] opened 2021-06-29 09:16 UTC
The node data for a lineage query returns a duplicate `type` field. For more details, see https://github.com/MarquezProject/marquez/pull/1457#issuecomment-868370913

**Comment by julienledem** [comment] 2021-09-14 15:54
duplicate of https://github.com/MarquezProject/marquez/issues/1527

**Closed** 2021-09-14 15:54 UTC
Labels: bug
